### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by Timple** [nobleo/path_tracking_pid#117]
![image](https://user-images.githubusercontent.com/5036851/156180919-621615dd-2525-4368-a8cd-94212db0572b.png)

This is not a proper forward prediction of the vehicle footprint.

Test probably 'succeeds' because of poor criteria.

**Comment by lewie-donckers** [comment]
Hmmm. Haven't seen that yet. Even though I have been running all tests with visualization a lot lately to check for regressions.

What branch was that?

**Comment by Timple** [comment]
@Rayman also could not reproduce. I'll try tomorrow!

**Comment by Timple** [comment]
Cannot reproduce
