### ISSUE TITLE
`Controller::distToSegmentSquared()` should be refactored

### ISSUE THREAD

**Issue by lewie-donckers** [nobleo/path_tracking_pid#122]
I think `Controller::distToSegmentSquared()` should be refactored in several ways:

1.  Its name suggests it calculates a distance but the main purpose is to determine a pose: the closest pose on segment. I propose we change the name to reflect this.
1. Beside the pose, it also returns distances but these can easily be calculated by the caller (if required). I propose we remove those distances from the output.
2. It's currently a const member function but it only uses the data member `estimate_pose_angle_enabled_`. I propose we replace that with an input parameter.
3. If the previous point has been done, the function can be extracted (to `calculations.h/cpp` for example) and unit tests can be added.
4. To do this, `distSquared()` from the anonymous namespace in `controller.cpp` would have to be moved too. I propose we do this and add unit tests for that as well.

**Comment by rokusottervanger** [comment]
I approve!

**Comment by cesar-lopez-mar** [comment]
I also agree, it should be more explicit what the function really does.
