### ISSUE TITLE
Controller's end phase distance is calculated wrong for backwards motion

### ISSUE THREAD

**Issue by PaulVerhoeckx** [nobleo/path_tracking_pid#145]
`d_end_phase` ([here](https://github.com/nobleo/path_tracking_pid/blob/dbe631d210f389466cc3069651588aff1ce39818/src/controller.cpp#L448-L460)) can result in negative values if `target_x_vel` < 0

**Comment by cesar-lopez-mar** [comment]
I think the issue is not whether d_end_phase is negative but how its value is used. Negative d_end_phase just means that the robot will end it's current phase at a position behind the current position
