### ISSUE TITLE
Possible unsigned underflow

### ISSUE THREAD

**Issue by Rayman** [nobleo/path_tracking_pid#48]
PR #25 changed this line:

https://github.com/nobleo/path_tracking_pid/blob/b5c139119c74602a2421fec024e3cded41fac821/src/controller.cpp#L122

@lewie-donckers I think this is quite dangerous. If `pose_idx` is an unsigned int, that means that this comparison can underflow when global plan is empty.

_Originally posted by @Rayman in https://github.com/nobleo/path_tracking_pid/pull/25#r806908279_

**Comment by Timple** [comment]
Lets fix this. Or assert it to be non-zero if it cannot be.
