### ISSUE TITLE
Controller reconfigures itself on cancel

### ISSUE THREAD

**Issue by rokusottervanger** [nobleo/path_tracking_pid#49]
When cancelling the `exe_path` action, the controller changes the configuration set by the user: it sets `target_x_vel` to zero, and it never changes it back. As a result, the next goal sent on the `exe_path` action interface is not executed well, because the `target_x_vel` remains zero.

**Comment by Timple** [comment]
Solution would be to have an internal setpoint. This get's reconfigured when the reconfigure is called. But this one can also be set to zero without influencing the nodes parameter.

**Comment by rokusottervanger** [comment]
I would say set a velocity limit just like the ones referenced below. Is that not good enough?

https://github.com/nobleo/path_tracking_pid/blob/b5c139119c74602a2421fec024e3cded41fac821/src/controller.cpp#L919-L934

**Comment by Timple** [comment]
Ah, implement is as a limit. That could work as well!

**Comment by rokusottervanger** [comment]
Only concern here might be that this inhibits the velocity directly, meaning that the output may step to zero. I believe, but I'm not sure the `target_x_vel` is allowed to make steps like that, because they would be smoothed by the controller's dynamic limits (acceleration, jerk?).

**Comment by Timple** [comment]
Yes, it currently is smoothed. An should do so in the new implementation as well.

But all limits are currently smoothed as well right?

**Comment by rokusottervanger** [comment]
Not sure. I haven't had the time to look into it yet, but it just crossed my mind. This seemed like the right place to make a note of that ;)

**Comment by rokusottervanger** [comment]
This is a duplicate of #9
